/*
 *
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultSetDialogBox.java
 *
 * Created on 10-Apr-2011, 18:04:50
 */

package sqlitejviewer;

import javax.swing.JFrame;

/**
 *
 * @author Richard
 */
public class ResultSetDialogBox extends javax.swing.JDialog {
    private String dataObjectName;
    /** Creates new form ResultSetDialogBox */
    public ResultSetDialogBox(JFrame parent, boolean modal, String dataObjectName) {
        super(parent, modal);
        this.dataObjectName = dataObjectName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultSetPanel = new ResultSetPanel(dataObjectName);
        exportDataButton = new javax.swing.JButton();
        refreshDataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        exportDataButton.setText("Export Data");

        refreshDataButton.setText("Refresh (F5)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultSetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exportDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshDataButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultSetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportDataButton)
                    .addComponent(refreshDataButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportDataButton;
    private javax.swing.JButton refreshDataButton;
    private sqlitejviewer.ResultSetPanel resultSetPanel;
    // End of variables declaration//GEN-END:variables

}
