/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultSetPanel.java
 *
 * Created on 10-Apr-2011, 17:01:09
 */

package sqlitejviewer;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.TableModel;

/**
 *
 * @author Richard
 */
public class ResultSetPanel extends javax.swing.JPanel {
    private String tableName;

    /** Creates new form ResultSetPanel */
    public ResultSetPanel() {
        initComponents();
        resultSetTable.setModel(new ResultSetTableModel());
    }

    public ResultSetPanel(String tableName) {
        
        initComponents();

        TableModel resultSetTableModel = MainFrame.dbInteractor.getTableData(tableName);
        resultSetTable.setModel(resultSetTableModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultSetScrollPane = new javax.swing.JScrollPane();
        resultSetTable = new javax.swing.JTable();

        resultSetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultSetScrollPane.setViewportView(resultSetTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultSetScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultSetScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane resultSetScrollPane;
    private javax.swing.JTable resultSetTable;
    // End of variables declaration//GEN-END:variables

}
