package sqlitejviewer.gui;

import javax.swing.table.TableModel;

/**
 * The container for the JTable that has a ResultSetTableModel.
 *
 * @author Richard Hawkes
 */
public class ResultSetPanel extends javax.swing.JPanel {
    private String dataObjectName;

    /** Creates new form ResultSetPanel */
    public ResultSetPanel() {
        initComponents();
        resultSetTable.setModel(new ResultSetTableModel());
    }

    public ResultSetPanel(String dataObjectName) {
        this.dataObjectName = dataObjectName;
        initComponents();
        TableModel resultSetTableModel = MainFrame.dbInteractor.getAllData(dataObjectName);
        resultSetTable.setModel(resultSetTableModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultSetScrollPane = new javax.swing.JScrollPane();
        resultSetTable = new javax.swing.JTable();

        resultSetTable.setAutoCreateRowSorter(true);
        resultSetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultSetScrollPane.setViewportView(resultSetTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultSetScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultSetScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane resultSetScrollPane;
    private javax.swing.JTable resultSetTable;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the resultSetTable
     */
    public javax.swing.JTable getResultSetTable() {
        return resultSetTable;
    }

}
